### ISSUE TITLE
PHP-Errors in nextcloud log

### ISSUE THREAD

**Issue by mills1975** [PhieF/CarnetNextcloud#106]
When using carnet in nextcloud, I get the following errors in log:

- [PHP] Error: Only variables should be passed by reference at /home/users/princessandhoney/www/nextcloud/apps/carnet/lib/Misc/CacheManager.php#98

- [PHP] Error: fclose(): supplied resource is not a valid stream resource at /home/users/princessandhoney/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#981

- [PHP] Error: Undefined variable: res at /home/users/princessandhoney/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#839

- [PHP] Error: Invalid argument supplied for foreach() at /home/users/princessandhoney/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#839

The errors occur simply on creating or editing notes in carnet

 - OS (client): Windows 7
 - Browser: Firefox 73.0.1
 - Version 0.20
 - Nextcloud v18.0.1 on Debian 9 Server, MariaDB, Apache

**Comment by Starkstromkonsument** [comment]
+1

**Comment by theyoungstone** [comment]
+1, fresh install and:

{"reqId":"zZ7av4wWiWIzvILc5Xrq","level":3,"time":"2020-04-07T12:05:36+00:00","remoteAddr":"86.237.70.41","user":"pierre","app":"PHP","method":"POST","url":"/index.php/apps/carnet/note/saveText","message":"fclose(): supplied resource is not a valid stream resource at /var/www/html/nextcloud/apps/carnet/lib/Controller/NoteController.php#981","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.3.0","id":"5e8c6ece503ae"}
{"reqId":"zZ7av4wWiWIzvILc5Xrq","level":3,"time":"2020-04-07T12:05:36+00:00","remoteAddr":"86.237.70.41","user":"pierre","app":"PHP","method":"POST","url":"/index.php/apps/carnet/note/saveText","message":"Only variables should be passed by reference at /var/www/html/nextcloud/apps/carnet/lib/Misc/CacheManager.php#98","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.3.0","id":"5e8c6ece503ca"}

- OS (client): Xubuntu 64bits 19.10
- Browser: Firefox 74.0.1
- Version 0.20
- Nextcloud v18.0.3 on Debian 10 Server, MariaDB, Apache

**Comment by DonGitToTheMax** [comment]
I have the same problem. The App works fine but it is flooding my nextcloud logfile with error messages. With nearly every letter I type in carnet it creates another error message. 


Error | PHP | fclose():  supplied resource is not a valid stream resource at  /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#978 |  
-- | -- | -- | --


Error | PHP | Only variables should be passed by reference at /var/www/nextcloud/apps/carnet/lib/Misc/CacheManager.php#98 |  
-- | -- | -- | --


Error | PHP | Only variables should be passed by reference at /var/www/nextcloud/apps/carnet/lib/Misc/CacheManager.php#98 |  
-- | -- | -- | --

**Comment by theyoungstone** [comment]
It seems to be solved into v18.0.5.1.

**Comment by dominiquefournier** [comment]
The problem persists in the 0.22.2 version

**Comment by dominiquefournier** [comment]
Pull-request #123 should solve that

**Comment by locness3** [comment]
Shouldn't we close the issue now?

**Comment by Joe7new** [comment]
> 
> 
@dominiquefournier  Hi ! tTried carnet in Nextcloud today, works , but described php-errors are still there and floodling protocol ..is there a plan to fix that ?
regards Joe

**Comment by dominiquefournier** [comment]
For me with  the patch, there is no more error. Did you apply it ?

**Comment by PhieF** [comment]
The patch was merged, I don't know then ?

**Comment by Joe7new** [comment]
> 
> 
> For me with the patch, there is no more error. Did you apply it ?
Sorry, where is the patch ? And how to use ? Thanks . With kind regards, Joe

**Comment by dominiquefournier** [comment]
Pull-request #123 should solve that

**Comment by Joe7new** [comment]
Do I have to copy the php-code manually in CacheManager.php ? (edit CacheManager.php with php-editor ?)
